@startuml
'https://plantuml.com/sequence-diagram


class Telecommande{


   + allumerAppareils(Int)
   + eteindre(Int)
   + activerTout()
   + toString() : String
   + ajouterAppareils(Appareils)
}
class (Lampe){
- nom : String
- allumer : boolean
+ toString() : String

}
class Hifi{
- son : int
-allumer : boolean
+ allumer()
+ toString() : String
}

class Television{
-allumer : boolean
+allumer()
+eteindre()
}

interface Appareils{

+ toString() : String
+ isAllumer() : boolean
}

Hifi ..|> Appareils
Lampe ..|> Appareils
Television ..|> Appareils
Telecommande "*" --> "*"  Appareils : - appareils
@enduml